version: '3'
services:
  backend:
    image: intaniger/smartfarm_backend
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - ./:/go/src/github.com/rod41732/cu-smart-farm-backend
    environment:
      - GIN_MODE=debug
    command: ["sh","-c","go run main.go & go run ./service/main.go"]
    ports:
     - "3000:3000"
    links:
     - mongodb
     - iot_service_pack
  mongodb:
    image: mongo
    volumes:
     - "./mongodb:/data/db"
    ports:
     - "27017:27017"
  iot_service_pack:
    image: "intaniger/iot_server:1.1"
    ports:
#     - "1880:1880"
#     - "1883:1883"
#     - "8083:8083"
     - "8090:8086"
